name: db_j2ee

services:
  database:
    image: mysql:latest
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: '1234Azerty'
      MYSQL_DATABASE: 'example'
    volumes:
      - mysqldb:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysqldb:
    driver: local
